title: Adam G
description:
theme: null
layouts_dir: ./app/templates
includes_dir: ./app/templates
markdown: kramdown
plugins:
  - kramdown
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-relative-links